### ISSUE TITLE
Create activity page

### ISSUE THREAD

**Issue by Diogo-Ferreira** [HE-Arc/rencontres-activites#3]
Create the create activity page.

**Comment by Diogo-Ferreira** [comment]
For now you can:
- create an activity
- update an activity
- set location with google maps thanks to django-geolocation
- bootstrap forms thanks to https://github.com/GabrielUlici/django-bootstrap4

TODO:
- auto selection of the admin (the creator)
- more stylish selection of participants ( Recents friends, and a carousel view)
- date input
- more robust validations

**Comment by greut** [comment]
@Diogo-Ferreira 

django-geoposition utilise un `CharField`: https://github.com/philippbosch/django-geoposition/blob/master/geoposition/fields.py

Alors que Django vous propose d'utiliser les véritables types : https://docs.djangoproject.com/fr/1.10/ref/contrib/gis/

PostGIS est normalement installé.

**Comment by greut** [comment]
@Diogo-Ferreira 

django-geoposition utilise un `CharField`: https://github.com/philippbosch/django-geoposition/blob/master/geoposition/fields.py

Alors que Django vous propose d'utiliser les véritables types : https://docs.djangoproject.com/fr/1.10/ref/contrib/gis/

PostGIS est normalement installé.

**Comment by greut** [comment]
Finalement, non... j'ai changé d'avis à voir. https://github.com/HE-Arc/webapp-server/blob/master/scripts/team2_compose.py#L134-L142

Mais je vous le remets très volontiers si nécessaire.

**Comment by Diogo-Ferreira** [comment]
Est-ce vraiment utile d'utiliser PostGIS si on veut juste avoir la position (Lat,Long) ? La solution présente me paraît adaptée pour le contexte.

**Comment by Ishydo** [comment]
Utiliser des champs spatiaux c'est surtout cool pour calculer des distances / surfaces et/ou faire des queries en fonction de ça. 🛰 

Pour afficher des markers sur google-map pas besoin de se donner tant de mal j'pense 🗺 

( https://docs.djangoproject.com/fr/1.10/ref/contrib/gis/db-api/#distance-queries )

**Comment by greut** [comment]
ça dépend vous envisagez un jour de proposer une fonction de recherche ou pas.

On peut très bien stocker des dates en `VARCHAR` tant qu'on ne n'a pas besoin d'effectuer des actions de type `MONTH`/`YEAR`/...
Objectivement stocker un nombre en tant que chaîne de caractères, c'est n'est pas incroyable.

**Comment by greut** [comment]
> - Recherches d’activités
>
> -- _README.rst_

**Comment by greut** [comment]
https://djangopackages.org/grids/g/maps/

**Comment by Diogo-Ferreira** [comment]
On est passé a postgres c40a7b47b51c11d153daa8905c64d4037e02cdb1 .

more stylish selection of participants ( Recents friends, and a carousel view) done, manque juste le queryset pour choisir des users spécifique à montrer.

**Comment by greut** [comment]
@Diogo-Ferreira plus qu'à passer à PostGIS à présent.

**Comment by Diogo-Ferreira** [comment]
@greut j'ai un peu peur que postgis ne soit pas compatible avec django-geoposition au niveau du widget qui est déjà implémenté. J'ai encore rien essayé, mais est-ce que ça vaut la peine de perdre du temps dessus ?

**Comment by greut** [comment]
django-geoposition c'est de l'agglo ;-)

**Comment by greut** [comment]
C'est ceci qui vous manquerait ?

https://github.com/philippbosch/django-geoposition/blob/master/geoposition/static/geoposition/geoposition.js

**Comment by Diogo-Ferreira** [comment]
Yep c'est ça

**Comment by greut** [comment]
Si c'est une idée qui vous motive, faite-le si non, conservez votre solution.

- https://docs.djangoproject.com/en/1.10/ref/contrib/gis/forms-api/#widget-classes
- https://developers.google.com/maps/documentation/javascript/places-autocomplete

**Comment by Diogo-Ferreira** [comment]
![image](https://cloud.githubusercontent.com/assets/2197937/24117296/f72ce83a-0da9-11e7-8c8f-d928329ad69e.png)
Et hop une bonne vieille carte postgis

**Comment by Diogo-Ferreira** [comment]
@greut c'est bon, j'ai trouvé de quoi faire jolie comme avant sans trop d'effort : https://github.com/erdem/django-map-widgets

**Comment by greut** [comment]
Postgis c'est Postgres, vous devez parler d'OpenStreetMap

**Comment by Diogo-Ferreira** [comment]
Oui, mais pour OpenStreetMap on doit spécifier OSMWidget, sinon on obtient un truc assez moche (screenshot d'avant). Mais bref je préfère : https://github.com/erdem/django-map-widgets.

Sinon il ne manque plus qu'à passer sous floppy-forms ou crispy-forms pour les customs widgets, et faire un champ date correct, après je pense avoir passé assez de temps sur cette page.

**Comment by greut** [comment]
très joli, en effet.
