### ISSUE TITLE
Login pages

### ISSUE THREAD

**Issue by Diogo-Ferreira** [HE-Arc/rencontres-activites#5]

**Comment by Ishydo** [comment]
Testé et approuvé

https://django-registration.readthedocs.io/en/2.2/

:fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire: :fire:

**Comment by greut** [comment]
@Ishydo j'ai eu plus de chance avec : https://django-registration-redux.readthedocs.io/en/latest/

@Diogo-Ferreira ceci est pour avoir un formulaire d'inscription. Pour un simple _login_, rien de spécial n'est nessaire: https://docs.djangoproject.com/en/1.10/topics/auth/default/#using-the-views
